baseURL = "https://eventfd.github.io"
languageCode = "en-us"
title = "Suvaditya Sur"
theme = "typo"

[params]
description = "eventfd"
disableSocialMeta = true
theme = "auto"
colorPalette = "default"
singleDateFormat = "2 Jan 2006"
hideHeader = false
homeIntroTitle = "Hi!"
homeIntroContent = """
I'm a **Software Engineer** with a strong foundation in computer science and a love for problem-solving. My interests include algorithms, compiler design, operating systems, and functional programming—especially **Haskell**. I enjoy understanding systems from first principles and exploring how high-level abstractions map to real machines.

I'm motivated by the challenge of breaking complex systems down until they're simple enough to truly understand.

This blog is where I share things I'm learning or experimenting with, as well as notes from challenges and projects that catch my interest.

### Achievements (Summary)
- AIR 145 — GATE CS 2021
- Rank 1 — InCTF 2019
- Top 20 globally in Flare-On
- Rank 7 globally in Decompetition
- Rank 2 globally in Malware Bytes CTF (Fastest Solver Category)

[See full list →](/achievements/)

"""
# Collection to display on home
homeCollectionTitle = ""
homeCollection = ""

# Lists parameters
paginationSize = 5
listSummaries = true
listDateFormat = "2 Jan 2006"

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "leetcode"
url = "https://leetcode.com/eventfd"

# Main menu pages

[[params.menu]]
name = "articles"
url = "/articles"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "achievements"
url = "/achievements"


# Syntax highlight on code blocks
[markup]
    [markup.highlight]
        noClasses = false
        lineNos = true
        lineNumbersInTable = false
        guessSyntax = true
    [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
            block = [['\[', '\]'], ['$$', '$$']]
            inline = [['\(', '\)'], ['$', '$']]
